#!/usr/bin/env python3
import argparse
import sys

from jwlib.arguments import add_arguments
from signs.parse import JWSigns


parser = argparse.ArgumentParser(prog='jw-signs',
                                 usage='%(prog)s [INPUT] [options] [DIR]',
                                 description='Split videos Bible jw.org sign language')
add_arguments(parser, ['--quiet',
                       '--book'])

parser.add_argument('input',
                    metavar='INPUT DIR',
                    help='input directory of file or folder')
parser.add_argument('--hwaccel',
                    action='store_true',
                    help='hardware acceleration nvidia')
parser.add_argument('work_dir',
                    metavar='OUTPUT DIR',
                    help='directory to save data in')
parser.add_argument('--raw',
                    action='store_true',
                    help='split videos without name parsing mark chapters')

"""
jw-signs '/Users/bastianpalavecino/Desktop/nwt-LSCH Descargas' '/Users/bastianpalavecino/Desktop/cortes'
jw-signs '/Users/bastianpalavecino/Desktop/nwt-LSCH Descargas' --book 40 '/Users/bastianpalavecino/Desktop/cortes'
jw-signs '/Users/bastianpalavecino/Desktop/vbastianpc/nwt_57_Phm_SCH_01_r480P.mp4' '/Users/bastianpalavecino/Desktop/cortes'
"""


jw = JWSigns()
parser.parse_args(namespace=jw)
# print(vars(jw))
# print(*jw.get_match_videos(), sep='\n', end='\n')
# print(*jw.get_cutup_verses(), sep='\n', end='\n')

try:
    if jw.raw:
        r = jw.raw_parse()
    else:
        r = jw.parse()
    jw.cook(r)
except KeyboardInterrupt:
    if hasattr(jw, 'finished_event'):
        jw.finished_event.set()
    print('\n\nCancelled')
    exit(1)
