#!/usr/bin/env python3
import argparse
import os
from sys import stderr

from jwlib.arguments import disk_usage_info, add_arguments
from jwlib.parse import JWBroadcasting
import jwlib.output as jo


parser = argparse.ArgumentParser(prog='jwb',
                                 usage='%(prog)s [options] [DIR]',
                                 description='Index or download media from tv.jw.org')
parser.add_argument('--type',
                    default='video',
                    choices=['video'])

# The commented out options would only be valid with a --config file
add_arguments(parser, ['--quiet',
                       '--mode',
                       '--lang',
                       '--quality',
                       '--burned-subtitles',
                       '--subtitles-only',
                       '--download',
                       '--no-download',
                       '--title',
                       # '--checksum',
                       '--no-checksum',
                       'work_dir'])
# TODO
# parser.add_argument('--config')
parser.add_argument('--category',
                    dest='index_category',
                    help='comma separated list of categories to index',
                    metavar='CODE')
parser.add_argument('--exclude',
                    dest='exclude_category',
                    metavar='CODE',
                    help='comma separated list of categories to exclude from download')
parser.add_argument('--latest',
                    action='store_const',
                    const='LatestVideos',
                    dest='index_category',
                    help='index the "Latest Videos" section')
parser.add_argument('--since',
                    metavar='YYYY-MM-DD',
                    dest='mindate',
                    help='only index media newer than this date')
parser.add_argument('--limit-rate',
                    default='1M',
                    dest='rate_limit',
                    help='maximum download rate, passed to curl (0 = no limit)')

jwb = JWBroadcasting()

# Default values, not set by JWBroadcasting
jwb.work_dir = '.'
jwb.warn = False
jwb.clean = False
jwb.ntfs = False
jwb.exclude_category = 'VODSJJMeetings'
parser.parse_args(namespace=jwb)

wd = jwb.work_dir
print('type', jwb.type)
r = jwb.parse()

jwb.prepare_download()
jwb.manage_downloads()

# jwb.download_all(os.path.join(wd, subdir))

if not jwb.download:
    jo.output_stdout(r, wd)
